import Head from 'next/head'
import Image from 'next/image'
import { Fragment } from 'react/cjs/react.production.min'
import Menu from '../components/menu';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Fragment>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Finances</a>
          </h1>
        </main>
      </div>
      <Menu />
    </Fragment>
  )
}
